version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_example

  backend1:
    build:
      context: ./backend1
    ports:
      - "5000:5000"
    depends_on:
      - db

  backend2:
    build:
      context: ./backend2
    ports:
      - "5001:5001"
    depends_on:
      - db
